### ISSUE TITLE
C++/CLI interop benchmark

### ISSUE THREAD

**Issue by fbrosseau** [ltrzesniewski/Benchmarks#1]
Hello

For complete fairness to C++/CLI (at least under .netfx), it would need to be compiled as /CLRUNMANAGEDCODECHECK:NO, so that the implicit DllImport stubs are decorated with SuppressUnmanagedCodeSecurity.

I would then expect that test to behave pretty much like the C# one.

**Comment by ltrzesniewski** [comment]
Hi, thanks for your comment!

The C++/CLI part is already compiled with this flag: https://github.com/ltrzesniewski/Benchmarks/blob/820f0d409f511fcf10bf160addfd4f4265aef939/NativeInterop/NativeInterop.CppCli/NativeInterop.CppCli.vcxproj#L74

For me, the C++/CLI perf is on par with P/Invoke. You get a bit of extra overhead when calling the dll function because there's an additional indirection. The managed code calls a compiler-generated native method which calls the dll.
If you implement the native method directly in the C++/CLI  assembly, you understandably get better performance. This is the `CppCliDirect` benchmark.

**Comment by fbrosseau** [comment]
Ha, I completely missed it, I thought I looked carefully!

Thanks.
